---
apiVersion: v1
kind: Namespace
metadata:
  name: service
  labels:
    name: service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
        version: "1"
    spec:
      containers:
      - name: hello-world
        image: zioalex/hello_world_app:1
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
  selector:
    app: hello-world
